attrib +s +h Sounds
attrib +s +h SteamLibrary
attrib +s +h storage
attrib +s +h scan
attrib +s +h Ringtones
attrib +s +h Recordings
attrib +s +h Podcasts
attrib +s +h Pictures
attrib +s +h Notifications
attrib +s +h Music
attrib +s +h .mediaexplorer
attrib +s +h Alarms
attrib +s +h Android
attrib +s +h Audiobooks
attrib +s +h conf
attrib +s +h DCIM
attrib +s +h Documents
attrib +s +h Download
attrib +s +h Huawei
attrib +s +h HuaweiSystem
attrib +s +h 2B1F6319EE2C75F2F8E49F3117645462E36CFB22.torrent
attrib +s +h sep
attrib +s +h sep1
attrib +s +h include
attrib +s +h ItemTemplates
attrib +s +h jmods
attrib +s +h kugou
attrib +s +h legal
attrib +s +h lib
attrib +s +h LOST.DIR
attrib +s +h Movies
attrib +s +h logo.ico
attrib +s +h autorun.inf
attrib +s +h 新建文件夹
attrib +s +h COPYRIGHT
attrib +s +h release
attrib +s +h LICENSE